[package]
name = "zkpoker_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
log = "0.4.27"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
