[package]
name = "poker_gui"
description = "gui for poker client"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
ewebsock = { version = "0.8.0", features = ["tls"] }
poker-cards = { workspace = true, features = ["egui"] }
poker-core = { workspace = true }
indoc = "2"
log = { workspace = true }
serde = { workspace = true }
snow = { workspace = true }

[target.'cfg(not(target_os = "linux"))'.dependencies]
eframe = { workspace = true, features = [
    "default_fonts",
    "glow",
    "persistence",
] }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { workspace = true, features = [
    "default_fonts",
    "glow",
    "x11",
    "persistence",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.3", features = ["wasm_js"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["net", "rt"] }
aws-lc-sys = { version = "0.29.0", features = ["bindgen"] }
